#pragma once 
#include <iostream>
#include <string>
#include "BST.h"
#include "list_of_repated_topic.h"
#include "list_of_topics.h"
#include "node_bst.h"
#include "node_of_repated_topic.h"
#include "node_sem.h"
#include "node_topic.h"
#include "semesters.h"
#include "student.h"